theme: minima
title: Sandwiches, Everyone Loves Them
author: Chris Crowder
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sandwiches everyone loves them, here are some of my favorites.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
